#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Generate include/prompts.h from the two editable lists at the top of src/main.cpp.

  IMAGERY_TO_USE[]     motifs (水滴, 二向箔, 黑暗森林 ...)
  PROMPT_TEMPLATES[]   narrative openers containing {意象}

Every motif is substituted into every template, so the header carries the whole
cross product already tokenized (20 x 8 = 160 prompts). The device ships a
decode-only tokenizer and cannot tokenize at runtime, so the combinations must be
baked in.

WHY NOT ASSEMBLE THEM ON THE DEVICE
-----------------------------------
It looks tempting: tokenize the motifs and the template halves separately, then
concatenate the token ids. But sentencepiece marks word boundaries, and a
fragment tokenized in isolation picks up a leading space marker (this tokenizer
stores 我 as " 我"). Spliced mid-sentence that renders as a visible gap. Baked
whole strings have no such seams, and the flash cost is trivial.

Usage (normally invoked by tools/pio_prompts.py on every build):
    python scripts/gen_prompts.py
    python scripts/gen_prompts.py --check      # exit 1 if prompts.h is stale
"""
import argparse
import os
import re
import shutil
import sys
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MAIN_CPP = os.path.join(ROOT, "src", "main.cpp")
OUT = os.path.join(ROOT, "include", "prompts.h")
SP_MODEL = os.path.join(ROOT, "data", "tok8192.model")

IMAGERY_BEGIN = "IMAGERY_BLOCK_BEGIN"
IMAGERY_END = "IMAGERY_BLOCK_END"
TMPL_BEGIN = "TEMPLATE_BLOCK_BEGIN"
TMPL_END = "TEMPLATE_BLOCK_END"

PLACEHOLDER = "{意象}"
LITERAL = re.compile(r'"((?:[^"\\]|\\.)*)"')

# The whole point of the piece is that the being is alone and confined, so the
# opening must not come round again within a viewer's patience.
MIN_COMBOS = 100


def unescape(s):
    out, i = [], 0
    while i < len(s):
        if s[i] == "\\" and i + 1 < len(s):
            nxt = s[i + 1]
            out.append({"n": "\n", "t": "\t", "r": "\r", '"': '"', "\\": "\\"}.get(nxt, nxt))
            i += 2
        else:
            out.append(s[i])
            i += 1
    return "".join(out)


def escape(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')


def block_literals(text, begin, end, label):
    """String literals inside a marked block, with line comments stripped.

    Comments are removed before scanning so commented-out examples are not picked
    up. Prompts never contain '//', so a simple split is safe here.
    """
    try:
        a = text.index(begin)
        b = text.index(end, a)
    except ValueError:
        raise SystemExit(f"could not find the {label} markers in {MAIN_CPP}")
    body = []
    for line in text[a:b].splitlines():
        if "//" in line:
            line = line.split("//", 1)[0]
        body.append(line)
    out = [unescape(m.group(1)) for m in LITERAL.finditer("\n".join(body))]
    out = [s for s in out if s.strip()]
    if not out:
        raise SystemExit(f"no strings found in the {label} block of {MAIN_CPP}")
    return out


def build_header(imagery, templates, sp):
    # IMAGERY-MAJOR, so that flat index = motif * NUM_TEMPLATES + template. The
    # firmware decodes it that way (motif = i / NUM_TEMPLATES, template = i %
    # NUM_TEMPLATES) and picks the 意象 card text from the same index.
    #
    # Looping template-major instead -- which this script did at first -- produces
    # a header of exactly the right size and a device that displays one motif on
    # the card while feeding the model a different one. Nothing crashes and every
    # count looks right; the ritual is just quietly wrong forever.
    combos = []                      # (imagery_index, template_index, text)
    for ii, m in enumerate(imagery):
        for ti, t in enumerate(templates):
            if PLACEHOLDER not in t:
                raise SystemExit(f"template {ti} has no {PLACEHOLDER}: {t}")
            combos.append((ii, ti, t.replace(PLACEHOLDER, m)))

    # self-check: the index arithmetic the firmware relies on must hold
    for k, (ii, ti, _) in enumerate(combos):
        assert k // len(templates) == ii and k % len(templates) == ti, \
            f"index {k} does not decode to motif {ii} x template {ti}"

    lines = [
        "// Auto-generated by scripts/gen_prompts.py -- DO NOT EDIT.",
        "//",
        "// Source of truth: IMAGERY_TO_USE[] and PROMPT_TEMPLATES[] at the top of",
        "// src/main.cpp. Edit those and press Upload; a pre-build hook regenerates",
        "// this header with every combination re-tokenized.",
        "//",
        "// Prompts are baked as whole strings on purpose. Splicing separately",
        "// tokenized fragments on the device would leave stray spaces where",
        "// sentencepiece placed its word-boundary marker.",
        "//",
        "// Each array starts with BOS(1); a trailing 0 terminates (0 is never a",
        "// valid token id). PROMPTS[] is flat, indexed imagery * NUM_TEMPLATES +",
        "// template.",
        "#pragma once",
        "#include <stdint.h>",
        "",
        f"static const int NUM_IMAGERY = {len(imagery)};",
        f"static const int NUM_TEMPLATES = {len(templates)};",
        f"static const int NUM_PROMPTS = {len(combos)};",
        "",
        '// motif names, for the "意象" card on the OLED',
        "static const char* const IMAGERY_TEXTS[] = {",
    ]
    for m in imagery:
        lines.append(f'    "{escape(m)}",')
    lines += ["};", ""]

    for k, (ii, ti, full) in enumerate(combos):
        ids = [sp.bos_id()] + sp.encode(full)
        lines.append(f"// imagery {ii} x template {ti}: {full}")
        lines.append(f"static const int32_t PROMPT_{k}[] = {{ {', '.join(str(x) for x in ids)}, 0 }};")
    lines.append("")
    lines.append("static const int32_t* const PROMPTS[] = {")
    for k in range(len(combos)):
        lines.append(f"    PROMPT_{k},")
    lines.append("};")
    lines.append("")
    return "\n".join(lines), combos


def load_tokenizer():
    # sentencepiece's C++ backend cannot open a non-ASCII path
    tmp = os.path.join(tempfile.gettempdir(), "espllm_genprompts")
    os.makedirs(tmp, exist_ok=True)
    dst = os.path.join(tmp, "tok8192.model")
    shutil.copy2(SP_MODEL, dst)
    import sentencepiece as spm
    return spm.SentencePieceProcessor(model_file=dst), tmp


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="only report whether prompts.h is up to date")
    a = ap.parse_args()

    if not os.path.exists(SP_MODEL):
        raise SystemExit(f"tokenizer model not found: {SP_MODEL}")

    text = open(MAIN_CPP, encoding="utf-8").read()
    imagery = block_literals(text, IMAGERY_BEGIN, IMAGERY_END, "IMAGERY")
    templates = block_literals(text, TMPL_BEGIN, TMPL_END, "TEMPLATE")

    n_combo = len(imagery) * len(templates)
    if n_combo < MIN_COMBOS:
        raise SystemExit(
            f"only {n_combo} combinations ({len(imagery)} motifs x {len(templates)} "
            f"templates); the ritual needs at least {MIN_COMBOS} so the opening "
            f"cannot repeat itself. Add more motifs or templates in src/main.cpp.")

    sp, tmp = load_tokenizer()
    try:
        header, combos = build_header(imagery, templates, sp)
        tok_counts = [len(sp.encode(f)) + 1 for _, _, f in combos]
    finally:
        shutil.rmtree(tmp, ignore_errors=True)

    old = open(OUT, encoding="utf-8").read() if os.path.exists(OUT) else None
    if old == header:
        print(f"prompts.h is up to date ({len(imagery)} motifs x {len(templates)} "
              f"templates = {n_combo} prompts)")
        return 0

    if a.check:
        print("prompts.h is STALE", file=sys.stderr)
        return 1

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(header)

    print(f"regenerated {os.path.relpath(OUT, ROOT)}: "
          f"{len(imagery)} motifs x {len(templates)} templates = {n_combo} prompts")
    print(f"  tokens per prompt: min {min(tok_counts)}, max {max(tok_counts)}, "
          f"total flash ~{sum(tok_counts) * 4 / 1024:.1f} KB")
    print(f"  motifs: {'、'.join(imagery)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
